### PR TITLE
Add CD_SILENT option

### PR DESCRIPTION
**Pull request by guidocella**

### CODE REVIEW

**Comment by danielshahaf** [comment]
Confirmed that no other recently-added options are missing.  The last few options added to zsh are:

```
% git blame zsh-5.8 Src/options.c | perl -nE 'print if /static struct optname optns\[\]/../;$/' | cut -c 32- | sort | tail
2014-06-13 21:39:44 +0100  188) {{NULL, "localloops",         OPT_EMULATE},              LOCALLOOPS},
2015-06-08 09:50:26 +0100  200)                               OPT_ALL
2015-06-18 14:54:41 +0100  180) {{NULL, "kshtypeset",         0},                        KSHTYPESET},
2015-06-29 19:01:31 +0100   85) {{NULL, "appendcreate",       OPT_EMULATE|OPT_BOURNE},   APPENDCREATE},
2015-10-30 12:28:07 +0000  146) {{NULL, "globstarshort",      OPT_EMULATE},              GLOBSTARSHORT},
2015-12-19 16:57:09 -0800  262) {{NULL, "warncreateglobal",   OPT_EMULATE},              WARNCREATEGLOBAL},
2017-01-10 19:14:26 +0000   81) {{NULL, "aliasfuncdef",       OPT_EMULATE|OPT_BOURNE},   ALIASFUNCDEF},
2017-01-23 09:50:57 +0000  263) {{NULL, "warnnestedvar",      OPT_EMULATE},              WARNNESTEDVAR},
2017-12-22 20:00:54 +0000  115) {{NULL, "checkrunningjobs",   OPT_EMULATE|OPT_ZSH},      CHECKRUNNINGJOBS},
2019-04-12 14:00:19 -0500  111) {{NULL, "cdsilent",           0},                        CDSILENT},
```

Two options have been added in zsh master since its last release: `SHORT_REPEAT` and `CLOBBER_EMPTY`.  Up to you whether to add them now or wait until they're released.  I don't anticipate any changes to these options before the next release (5.9).

**Comment by chrisbra** [comment]
> Two options have been added in zsh master since its last release: SHORT_REPEAT and CLOBBER_EMPTY

@guidocella  would you mind squashing those new options in as well? Thanks.

**Comment by guidocella** [comment]
Done.

**Comment by chrisbra** [comment]
Thanks!

**Pull request merged**
